Migrate navigation to react
urfu-2020/team-5 pull request #26
Opened 2021-04-25 20:20 UTC by Andreykch

- Переверстал список контактов на реакт
- Добавил кнопку-гамбургер главного меню приложения +обновил строку поиска
- Сделал подсветку кнопок при `:hover` круглой и добавил к кнопке стиль `:focus-visible`

2021-04-25 21:23 UTC, nomerdvadcatpyat requested changes
нашел опечатку в ариа лейбле

2021-04-25 21:23 UTC, nomerdvadcatpyat commented on client/src/components/Navigation/NavigationHeader/NavigationHeader.jsx
> +        <Button className="button" aria-label="Открыть нлавное меню" type="button">
`aria-label="Открыть нлавное меню"`
Очепятка

2021-04-25 21:26 UTC, Andreykch commented on client/src/components/Navigation/NavigationHeader/NavigationHeader.jsx
> +        <Button className="button" aria-label="Открыть нлавное меню" type="button">
Вроде в комите `Fix lint` пофикшено

2021-04-25 21:42 UTC, nomerdvadcatpyat approved these changes

2021-04-26 07:52 UTC, mariadyuzheva approved these changes

2021-04-26 11:47 UTC, merged